---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-helmrelease
  namespace: longhorn
spec:
  interval: 10m0s
  chart:
    spec: 
      chart: longhorn
      version: 1.10.1
      sourceRef:
        kind: HelmRepository
        name: longhorn-helmrepository
        namespace: flux-system
  values:
    defaultSettings:
      allowCollectingLonghornUsageMetrics: false
      defaultReplicaCount: 2
