---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-cluster
  namespace: authentik
spec:
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-db-secret
  storage:
    size: 16Gi
