---
apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:H8wcqCQqxFZPoRvgpAOk,iv:vVYGOLsY5ODZxoYeVvYpFm0z24tmu+0n9bRzZFVSBm0=,tag:8YJ+hV0f/ZASGx0T7OSWhQ==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:DrUaB+1PUka8rLx7/naQ,iv:ZZbCVxfkWDVQ6n1K1J+E2qx85aV8dhtoBkH2xGqP+cM=,tag:vZVqdkZeXIek/gycTaGXRw==,type:str]
sops:
    age:
        - recipient: age14e9960ys3tqpnr40memrdp8uac0f86wv326ykwkwrufgrv4a5dtsd58zd2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSEtHRktsV2tKZlZyaWkw
            K3pTbE01cGdXMW13WDVSTnZ1M0srUit4d3pFCi9yWXorUUo3MnNzNUlpcjRwQkdl
            Rk81cnJmT1Y1V21xNThyQ1hjVkVNVFUKLS0tIGc1VW1hZmtYNGIxdm55U1ljT2FK
            UEF0dVlibFZmRUpRSlZVMk5hQXJNdW8KerVjbyKZ0C9O36/7oh9l7c7l5azNWd+J
            Eo26b+DPXLL21nH/Okc5ZU8eM511HalhTlVfaH7JADY6+u9Pn75Kng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T14:08:09Z"
    mac: ENC[AES256_GCM,data:kpgAwUJJ+dxSLW/sRw8bpy3hQPacn5tGQWYLgzZs7C487WbCh/lVf3yckIhKz9ThOU5dCv0XFAFI6CHeEbyO7Yz8TIoPGCb1fjuXwRqZ0QUQ6JT8Ur0T7w2eFmucJ4O0qNqD3a3jrrwdqYy5GZRQOoCKi9zwygWKjK70BDpccGM=,iv:T2N9PeagZk5I3vcQbW4RjnYrW/2ru6UQXu+l/SE+7vc=,tag:vmj3wzTY+tPngHTOaRyH0Q==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.12.1
