apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:twDkNVJMpktPn5ODLuzh,iv:P63JPQOTzxqWMG6djxuc4HHsLuxjkiSxpZDZhlegAeM=,tag:iARIPmlvzWipwaejt6IFDg==,type:str]
sops:
    age:
        - recipient: age14e9960ys3tqpnr40memrdp8uac0f86wv326ykwkwrufgrv4a5dtsd58zd2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMXkzb0FWN1U3bEhiYTJC
            KzJJWXhzNlRFMUFCbGczQ0pBSzRaQUMrVzBJCk5VTVZLMlpra3lRSkhJY3U1V1M0
            YjRDNEhxYjhFM1NSbW05U3B5N1FWdjgKLS0tIFZtczlYOCtLcVBwVzBsRnBGcWV1
            QWEyZk5IODhqcWZRczliUGNuZHJOYW8KdpjnM+N1mrOxcDk6zQ6NOCcyGVOvvYCq
            O3aF0N2IArfHLni5zKvfaW+I+l4TzEi0KfAaD43F2GmccqwxH28H4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T12:34:04Z"
    mac: ENC[AES256_GCM,data:NMzj2N2QFbw5AyK9SuKMJZEhrhmaOpFbIt+NKu0cBkSQCmPJhSLm4o/exXj3TuEBleSrKKih9V+uefj2XXPjJBVYUEyeCNGx8Jxt1pU9oLT00raNC8QAxEbpVq6uWjpmtL4nCjqKW/jgyFNzSo5kkHngpT6VNl8qD+FHxrXsAFQ=,iv:79Pjh1KHOx2lbYbx4u0kUaMTXOnmBJEXwDgAZCdT4Vo=,tag:UMvOvjWOeMnPWFAivqbJvw==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.12.1
