---
apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:/Nhg23mTZ9rIjyY6Zd8s,iv:1cw/xud3eRU0DsHXlCb7eyO1W9KItt6LzUKT7z35AxU=,tag:Ny94gFLAP0fXesPLcvzaRA==,type:str]
sops:
    age:
        - recipient: age14e9960ys3tqpnr40memrdp8uac0f86wv326ykwkwrufgrv4a5dtsd58zd2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQlNlMVlmNFg5ZUFkWW1O
            Z24va3FUaE9rOUcrc0hiRlFQVTQxMmhXSGpVCnlaYkd6S2k0RmpHNEN4SkczSU9L
            YjQyZnlRbnA5TzNuYTZ6QnNjL3VBbGMKLS0tIHMvTlo4VC9ZaG9FYTlBTXRzSko4
            Q3VMN2RaendoRndDVmcvbTh2S2d5T1UK9TYYtBndON1GZtL3+6ad0O0m3s3YXw1D
            ueZje7hW6B8EdmubM4MytlWPNgqusGCW+YzMsTsqZPAAY2uhvsTYnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T12:47:28Z"
    mac: ENC[AES256_GCM,data:orwIv1+lbR/zbQOq1+aBXxiI8pXcDW1uF8OcAVJNMg1w1yEUN52FL2CF/oQsUDz4wRQAiwrEKMPTm1BRdQIByyd+IV2QVt5Rqu30OJxUNIbcVELmvpE1Zmdc+GmBxk5iOvgb8QpmOb3WnUaT1Z6ahGEdCrK48POvGuem8e9tXQw=,iv:Wu84qAgD3Q3ETaZ0ppVvkBiQgO8ovvUKVDY0baLfpmI=,tag:fNCfjEyiLqNdNOngj9tNhQ==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: authentik
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:vlicnmxSoZ/Z0THn0ssu,iv:+4mDxCo1yW4qO9SjPU8QJvdZveITJ2s99/qCJ8RpHJs=,tag:yXLmoRAVUxYFN/FrZRgrjg==,type:str]
sops:
    age:
        - recipient: age14e9960ys3tqpnr40memrdp8uac0f86wv326ykwkwrufgrv4a5dtsd58zd2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQlNlMVlmNFg5ZUFkWW1O
            Z24va3FUaE9rOUcrc0hiRlFQVTQxMmhXSGpVCnlaYkd6S2k0RmpHNEN4SkczSU9L
            YjQyZnlRbnA5TzNuYTZ6QnNjL3VBbGMKLS0tIHMvTlo4VC9ZaG9FYTlBTXRzSko4
            Q3VMN2RaendoRndDVmcvbTh2S2d5T1UK9TYYtBndON1GZtL3+6ad0O0m3s3YXw1D
            ueZje7hW6B8EdmubM4MytlWPNgqusGCW+YzMsTsqZPAAY2uhvsTYnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T12:47:28Z"
    mac: ENC[AES256_GCM,data:orwIv1+lbR/zbQOq1+aBXxiI8pXcDW1uF8OcAVJNMg1w1yEUN52FL2CF/oQsUDz4wRQAiwrEKMPTm1BRdQIByyd+IV2QVt5Rqu30OJxUNIbcVELmvpE1Zmdc+GmBxk5iOvgb8QpmOb3WnUaT1Z6ahGEdCrK48POvGuem8e9tXQw=,iv:Wu84qAgD3Q3ETaZ0ppVvkBiQgO8ovvUKVDY0baLfpmI=,tag:fNCfjEyiLqNdNOngj9tNhQ==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.12.1
