---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-helmrelease
  namespace: cert-manager
spec:
  interval: 10m0s
  chart:
    spec:
      chart: cert-manager
      version: v1.19.4
      sourceRef:
        kind: HelmRepository
        name: cert-manager-helmrepository
        namespace: flux-system
  values:
    crds:
      enabled: true
    replicaCount: 2
    extraArgs:
    - --dns01-recursive-nameservers=1.1.1.1:53,1.0.0.1:53
    - --dns01-recursive-nameservers-only
    podDnsPolicy: None
    podDnsConfig:
      nameservers:
        - "1.1.1.1"
        - "1.0.0.1"
