---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-certificate
  namespace: keycloak
spec:
  secretName: keycloak-local-icutum-es-tls
  issuerRef:
    name: cert-manager-cluster-issuer
    kind: ClusterIssuer
  commonName: "keycloak.local.icutum.es"
  dnsNames:
    - "keycloak.local.icutum.es"
