---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack-helmrelease
  namespace: kube-prometheus-stack
spec:
  interval: 10m0s
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 87.4.0
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack-helmrepository
        namespace: flux-system
  values:
    kubeEtcd:
      endpoints:
        - 192.168.1.3
        - 192.168.1.4
        - 192.168.1.5
    kubeControllerManager:
      endpoints:
        - 192.168.1.3
        - 192.168.1.4
        - 192.168.1.5
    kubeProxy:
      endpoints:
        - 192.168.1.3
        - 192.168.1.4
        - 192.168.1.5
    kubeScheduler:
      endpoints:
        - 192.168.1.3
        - 192.168.1.4
        - 192.168.1.5
    grafana:
      admin:
        existingSecret: kube-prometheus-stack-secret-grafana
    prometheus:
      prometheusSpec:
        retentionSize: 14.4GiB
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              resources:
                requests:
                  storage: 16Gi
