---
apiVersion: v1
kind: Secret
metadata:
  name: kube-prometheus-stack-secret-grafana
  namespace: kube-prometheus-stack
type: Opaque
stringData:
  admin-user: ENC[AES256_GCM,data:gvqR9ts=,iv:mSc5+P3iEhZjHnJIICzWBIOFyvN0HOCqqSZcQbM42ck=,tag:e3fUhAHUavBje3TMD8bbHA==,type:str]
  admin-password: ENC[AES256_GCM,data:AioidZrqe0+o8PMcBexngya0bqzKH/H6qXUoEhTGcaWt5L6I3lLKC9zVjD1zVH1O,iv:i/ZZgalsHnccjOLGANy4bDsZd7FuOMwYQyXgMVfGLA4=,tag:DR78xi5m+DP/1BT5I/ei8A==,type:str]
sops:
  age:
    - recipient: age14e9960ys3tqpnr40memrdp8uac0f86wv326ykwkwrufgrv4a5dtsd58zd2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWDNLajNTVlVqbTRNWEpY
        ajlHUEFmcHhRUXc3Mk84cnI5U1prVG1SS2xvCjhYaGJTNFhnZnZLemlVbWN4R2Fw
        eGZNeUJ1c3RmWDVMK3hkQkNYTmwxU1UKLS0tIEVmRlFqdHgxUFBhTVNkeTRVdWgr
        UnhHWEMzNjlZNmd6YUZhdjBOYXc5V2cKjcf/mFKl/VkKxl7aXYInagMu8nOU9Px6
        qCc5kT/ZvByPMgn56XxsPcrQrq58RgwTnuLvE1hV1kZPGTrdygCwMQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-15T18:07:33Z"
  mac: ENC[AES256_GCM,data:v9dp1b1povwfWMQ0q23fck1im2npemHDHRmUpRvzbpz5zSWkh5YtAmjFTwF33tiLHIeLHvDGogw8R+rVRkUUlvZ/WjOtkUQh4oJQrykTg5/2yus/Qj2KQHOyGgIKyfddGE7fcjBMdsTohRSHpjufvuvvdnpPbDya40RKDQWqqJc=,iv:abZ5UJza7rr7XX3agqYDH56f6iA6cBtc1A6tyF+Dyzc=,tag:e5/sdePqkF1LoGwf6Q8qpg==,type:str]
  encrypted_regex: ^(data|stringData|email)$
  version: 3.12.1
