---
apiVersion: v1
kind: Secret
metadata:
  name: kube-prometheus-stack-secret-grafana
  namespace: kube-prometheus-stack
type: Opaque
stringData:
  admin-user: ENC[AES256_GCM,data:MuV7/yk=,iv:xdQHYuqqUmPEKKkGS0JPqkzn/YH1uAZL96eJVGBXn+k=,tag:XwWiEDamZOHjs8bhfPcwhw==,type:str]
  admin-password: ENC[AES256_GCM,data:FYquMAMnC5HEKaC0hfU1,iv:DcXTN+PtKKr8uo50Ulg3RbnWDfcR9jGTaOUl7EPYOZ0=,tag:Gpgf8zAijsEzyNP/oK3zEw==,type:str]
sops:
  age:
    - recipient: age14e9960ys3tqpnr40memrdp8uac0f86wv326ykwkwrufgrv4a5dtsd58zd2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwa0x5YUdaZjV5cGc5TjN3
        akViNVdxTFRaaVpoR1AyN2JiVlhBalhZM0NZCjVOa3c5QWxFTTFEQW9QUjZrTERy
        cFVibXdoZzBQV0Jpejg3Rk5MdUhGcDgKLS0tIG1WeFUvQTdCeFJlK1FXb3htYnl1
        djBsMnZMY1hiVXVFVkhoQXJnQlRsalUKd5NPL6dSToobpaFXgZOdMjBtEx3bnwfe
        ttPer07gaKkJUiqNmVFA+cdLlXfgkDs6MKamFPMKr2OvtBaGWXJ8mA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-20T14:18:49Z"
  mac: ENC[AES256_GCM,data:Mqdlo1PbqAF4t4ItInnghM1NSD6K+jfCzAVLwKUYLADAOOk90YQncGff6H/kFZ/osCSFnX3DX9JFiQpRgldjqCaJ4800ThG+iFjLrZIVmb33SsObLopx889eBLYCwM8TSZnCTK1jHxkJPloO+U2VtU1wwpzoCtw9P1//Exk5bZo=,iv:pzxLemVwgNKKQaqPPhgSE5jH66C4x266iA8d2PbBeO0=,tag:StRWKRe6mG6k5HWtcz1toQ==,type:str]
  encrypted_regex: ^(data|stringData|email)$
  version: 3.12.1
