---
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-pihole-password
  namespace: external-dns
type: Opaque
stringData:
  pihole-primary-password: ENC[AES256_GCM,data:TdubIiQFrbDfVfvb0oXVMpOp8Bl7OsFC8fMwIpG8f71fU8KmM3C53d0j+Fhr0iWk,iv:/kw0SuZbtHX1j7XY8vvXK1ZjTwjPXFRFh2AWxVtmjZw=,tag:ux612qqiBDnV7zAFB52e/Q==,type:str]
  pihole-secondary-password: ENC[AES256_GCM,data:3YIHrTP+jmXLxEn5dRUktU3CltY/S0m75ThWxAdI+ShesQVsYidRapHjd1QS,iv:MiOXTJgB0mO6lIIPwLTUyitIlQDgMgHaVzaukrKofw0=,tag:g4UGtjygQk3dtIqSMgwLXQ==,type:str]
sops:
  age:
    - recipient: age14e9960ys3tqpnr40memrdp8uac0f86wv326ykwkwrufgrv4a5dtsd58zd2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITUkxNlJkUEhxNFZaMlV1
        R3RsN0JWVUZOMUk1QXYwTVpLRVVHTC9ZOEdBCi93SThDQ2N2bFFRSE9jY3NLSW5a
        eDZLc2hiWTJGOXBxd2VEUkNIQ2dVbDAKLS0tIEk2RGMyckJDOU9qTVM3cmdIME5B
        QVIwT0UzdzRpMVRJdmcvbEJuekMrZE0K+GWZAFiolSFZm629O//43D5sYxvswIoP
        X6Hs5axkGZFYEMA8EVX8e9cJzrJIJsp4RZMh7lOJ4/2stShp/i8CAw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-15T18:06:06Z"
  mac: ENC[AES256_GCM,data:nExBZ94qbGw3ouXGyL+770HX8AfsScRfqaPSZNX4jtImXaq7bKbgsLNpVXA2THk1fYbIzpDA5MrrhZZLoQ32E5/C87P4gxTT5NpNuJp5wGpw38tiOPgn2ivZKKgxOrM2DPLAniLvgYEWx6ohQ7pLe9ywmWEVWrN1ccCSX+LZeVY=,iv:/i+ND3y/ZmDqlHW6FM8z0i5oL6+NMJHyglqATHYR/XQ=,tag:Z26PjmSQDg7dv2Rr9IBysg==,type:str]
  encrypted_regex: ^(data|stringData|email)$
  version: 3.12.1
