---
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-pihole-password
    namespace: external-dns
type: Opaque
stringData:
    pihole-password: ENC[AES256_GCM,data:4PVGTnpmzjytXyNveMMs,iv:yVa8XIeGC1rQLxlz77kd6LMwMJuKtjoa+nNZrhM5sPc=,tag:QyJCjVJFL0wXmys6zP/y3Q==,type:str]
sops:
    age:
        - recipient: age14e9960ys3tqpnr40memrdp8uac0f86wv326ykwkwrufgrv4a5dtsd58zd2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUUFLdCtsKzJPZlc5aExu
            OGhTVE1UbXNFYVB5eFVtWFYrNVYvcXB4MVdjCnJRKys1MWJybGI1RDU2K0kwVmRH
            dEJwL2NBZVF1a1pIVm5GSCswRXF2KzgKLS0tIHhCQTBtZklQSVJsQWFZZGpFejhv
            anNEQWZQYUhaNWMrQk41V3lRZkdCeEUKzXoOPkF3RYBT0juMwFnu5XpgrFjaSF5V
            Fx6T64OepBYf49uHlVk3cFIP6szp/Mf+F542suWq1hgZg8ZTw/H1mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T22:51:18Z"
    mac: ENC[AES256_GCM,data:bmt0xh9YNn1A8Alm91pZZOJyQ5WsyHvFMqq5EHNaJqyjqXYzxqUIq7+Ey/HhH07/t54MT+2XYLJwIKDylUpaEdKt4cVmtSDEnsOMML8UTyqi7j+Pd9QZ4TQX8fU29TuRtmuEdbsdWJEd+yiSUaFkzYl4K/pGNr06s700mPlTe0g=,iv:m22tMgwpdiKUdAj1xgbBojdPtyxSa8bJ6s30tjudFkA=,tag:3C2dnKs/DELEewPLhzHOug==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.11.0
