---
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare-token
    namespace: external-dns
type: Opaque
stringData:
    cloudflare-token: ENC[AES256_GCM,data:wboV4xeM1UoYU1ILh+UJTou9aavN9okQF1orEz1X8+128S4sz4kRLA==,iv:FgGwj5zMwR4rcivO2sG8ULjtYOz+t0A4LEHX+xuBOPc=,tag:RXRsN6+5G3QsF1iUEDQfXw==,type:str]
sops:
    age:
        - recipient: age14e9960ys3tqpnr40memrdp8uac0f86wv326ykwkwrufgrv4a5dtsd58zd2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOc211aUlnRXpuSytVUWJH
            RUZrakVNUjVwOU52RTczMlFZNXZBYWd0SEY4ClNMaHhHUDV2VWU5QStvV2xkOStX
            NDd0R2M5QzlRaWlhejRxUjBWd3p2SWMKLS0tIHNQMkRTelV4U3ZMbVJTN2V1djZI
            THNwS2grejhiU1FtaXMyVHYzWDZ3WEEKrpkDCRWxNOniyWj4cNzWFi5Af8yqkwiv
            Tm/uFObxjl0H4Fsak793O0+5s4D0t9PTEyoIAs7wLmf1waW3IrJ3Pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T18:33:38Z"
    mac: ENC[AES256_GCM,data:e6w493SwC6NF8oBdEdQ0lPO0vQZOuzOJ2N2plX1OH0MIV5lMH5H7HkPpQzfA3aEE4Pud8XWNrqakT9oebCHn8Ir9mTpbsVpV2fqzEmgcU39Ffyt6ZFqei67Qblh6CK6XmS6iB9WiCm4hXN3waJ9jcGrRfS9W1N4Ds8q/K6ZLO0U=,iv:DL+s1xZFwy3rZtYUHVYbRPMMF1qPaijNRt74fXbQ+vQ=,tag:8ptFuazKFcidyIbINmJI1g==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.11.0
