services:
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    environment:
      - DEFAULT_COLOR_SCHEME=dark
    volumes:
      - ./homarr/configs:/app/data/configs
      - ./homarr/icons:/app/public/icons
      - ./homarr/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '7575:7575'
    restart: unless-stopped

  dash:
    image: mauricenino/dashdot:latest
    container_name: dash
    privileged: true
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
      DASHDOT_OS_LABEL_LIST: 'os,arch,up_since,dash_version'
      DASHDOT_SHOW_HOST: 'true'
      DASHDOT_CPU_TEMPS_MODE: 'avg,max'
      DASHDOT_NETWORK_LABEL_LIST: 'type,speed_up,speed_down,interface_speed,public_ip'
      DASHDOT_ACCEPT_OOKLA_EULA: 'true'
    volumes:
      - /:/mnt/host:ro
    ports:
      - '3001:3001'
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ./prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ./deluge/config:/config
      - /mnt/md0/media/downloads:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TIMEZONE}
    volumes:
      - ./sonarr/config:/config
      - /mnt/md0/media/tv:/tv
      - /mnt/md0/media/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TIMEZONE}
    volumes:
      - ./radarr/config:/config
      - /mnt/md0/media/movies:/movies
      - /mnt/md0/media/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TIMEZONE}
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ./jellyfin:/config
      - /mnt/md0/media/tv:/data/tvshows
      - /mnt/md0/media/movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
        - LOG_LEVEL=debug
        - TZ=${TIMEZONE}
    ports:
        - 5055:5055
    volumes:
        - ./jellyseerr:/app/config
    restart: unless-stopped

  jellystat-db:
    image: postgres:15.2
    container_name: jellystat-db
    environment:
      POSTGRES_DB: ${JELLYSTAT_DB_NAME}
      POSTGRES_USER: ${JELLYSTAT_DB_USER}
      POSTGRES_PASSWORD: ${JELLYSTAT_DB_PASSWORD}
    volumes:
      - /mnt/md0/media/jellystat:/var/lib/postgresql/data
    restart: unless-stopped

  jellystat:
    image: cyfershepard/jellystat:latest
    container_name: jellystat
    environment:
      POSTGRES_USER: ${JELLYSTAT_DB_USER}
      POSTGRES_PASSWORD: ${JELLYSTAT_DB_PASSWORD}
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: ${JELLYSTAT_JWT_SECRET}
    ports:
      - "8181:3000"
    volumes:
      - ./jellystat:/app/backend/backup-data
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TIMEZONE}
    volumes:
      - ./bazarr/config:/config
      - /mnt/md0/media/movies:/movies
      - /mnt/md0/media/tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
