---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-cluster
  namespace: keycloak
spec:
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: keycloak-db-secret
  storage:
    size: 8Gi
