---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-secret
    namespace: keycloak
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:dmupEfS+4jOHofiNgYzS,iv:Dh8PLZpoP0fZJKB5mzSJ99SKXAn89wq+zw8waSB69os=,tag:zU557eSpSWY5y7qvKssTPQ==,type:str]
sops:
    age:
        - recipient: age14e9960ys3tqpnr40memrdp8uac0f86wv326ykwkwrufgrv4a5dtsd58zd2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bmhLREN4YjNPdUx2Mysz
            NFpRL00xSVVLSlBaYmJJVWh0STh3ZjNnbmdVClFxcEk0S2gzTVUwbFBBclpyei9I
            bGw0b2tKQUxJcXFvSld3UjJGbTRiM3cKLS0tIFg2QjFHZFJxUXlObHVBZ0JzbVFt
            MUtiand3SHJINlM2c1lmWG03eXNPQmMK1cpU9+hGhMg2yePT0lCz/H3d9C2sXGUj
            CNKPBE+EY/nMlrrKa49UO50Ppbs7Q2AM3ZvkMrdznE1ZMpvAei3V7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T10:21:16Z"
    mac: ENC[AES256_GCM,data:CFn9gf0C38rT7uDMkwt5usTadEfjHQa1+p/cmx6CMAba8HiKnPeGHaQSVE28yvyJyrquuj5owETrm3HLmDWSujJJzrhr8nMw/fKBz8O01Qv0LDtQLQLP/ekk8vL6TC7X+T+AmMXwyllJOOoMW5R/8AbErmm5MgTX3OXaIyeT2O8=,iv:zh0RWSy3nG1O/ELeCO2FQx5weOe7DewaUAXh3WAQrkw=,tag:kIwCvwn6GcXSTc2oXo0jmg==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-secret
    namespace: keycloak
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Un3XMlqIx1M=,iv:xw2U/y/mj50uCGhpcKNla0WR1bEI/SPK6VwsHTXaw6Y=,tag:DaYMqQf9sGbl5YaJXmdPNg==,type:str]
    password: ENC[AES256_GCM,data:2SrSZHFbJLhUoNaDw8Pd,iv:sHKSW7O/jpmACcA3Uw4E3K3W0VZjlV9bGdUhR0q0CJY=,tag:0qjr/mHBf3T4cGQ4jJ4EaQ==,type:str]
    jdbc-uri: ENC[AES256_GCM,data:84hbaj3LdKDu2hqHXIn9SqSqjOT2DzzcpXEsKHERveSRmMyrRvPMBNeuPuTysM5vw6GQTVSQjx+E/cVr2KE9uq1qq1lTSli5WDrQ7EZ+B1j0zIvgpkKXfcSgt3ExLYe1JhpCbjdltg==,iv:I2weemUjcBufsDPZvmyQebPKDv85eMmJAFn3KJWO6EA=,tag:Z2FIkwCyagjIJG/Pg6qcIw==,type:str]
sops:
    age:
        - recipient: age14e9960ys3tqpnr40memrdp8uac0f86wv326ykwkwrufgrv4a5dtsd58zd2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bmhLREN4YjNPdUx2Mysz
            NFpRL00xSVVLSlBaYmJJVWh0STh3ZjNnbmdVClFxcEk0S2gzTVUwbFBBclpyei9I
            bGw0b2tKQUxJcXFvSld3UjJGbTRiM3cKLS0tIFg2QjFHZFJxUXlObHVBZ0JzbVFt
            MUtiand3SHJINlM2c1lmWG03eXNPQmMK1cpU9+hGhMg2yePT0lCz/H3d9C2sXGUj
            CNKPBE+EY/nMlrrKa49UO50Ppbs7Q2AM3ZvkMrdznE1ZMpvAei3V7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T10:21:16Z"
    mac: ENC[AES256_GCM,data:CFn9gf0C38rT7uDMkwt5usTadEfjHQa1+p/cmx6CMAba8HiKnPeGHaQSVE28yvyJyrquuj5owETrm3HLmDWSujJJzrhr8nMw/fKBz8O01Qv0LDtQLQLP/ekk8vL6TC7X+T+AmMXwyllJOOoMW5R/8AbErmm5MgTX3OXaIyeT2O8=,iv:zh0RWSy3nG1O/ELeCO2FQx5weOe7DewaUAXh3WAQrkw=,tag:kIwCvwn6GcXSTc2oXo0jmg==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.12.1
