---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-secret
    namespace: keycloak
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:Jdt1fkmbgpz5doxYURqa,iv:wmU8Kl7CvOuMhS59QjFnx9/LoKPdBGT10v3h36IELKE=,tag:ta/0m7QN9B3fbLcoqev7IQ==,type:str]
sops:
    age:
        - recipient: age14e9960ys3tqpnr40memrdp8uac0f86wv326ykwkwrufgrv4a5dtsd58zd2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubVdNSVV5MkxKK2NYMlJw
            Zm9sMVU4STcvUkdLYVcxQ3hOa3g2WlVWMTFzCkRDcnFwQ2xOOVJ5TE51UHU2TndV
            Sm5GVDhFY0RkQSt2cVlkZUU3TXpkcWcKLS0tIFZaNnd2RnRReVlaZFk5OE8yKzlV
            cFpoUHNSTVR4UEtySituZDlWR3U2dTgKZLTjkdlg0ZrIntO9+apI9NMWU4ahOwac
            BqY7rpcTd/Nzy5fyPfbsaMy43Fet9dkvuI7DEzZiaWuGltlKpHWz0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T10:35:40Z"
    mac: ENC[AES256_GCM,data:zLG5aBgN0dIwt5fw/Clb34Ajv8GgmD3nNcVqlrm4Y81QIxcC3TDXrzgGllODcO5LTiF7gReeexYPTZsg57baaqtMnk7DaqYgjXYG6aJ7rfpKuYp/7a5X9kgW4ghJMp88/3PdtxJWEq0nBu3O297rMZ1s+/VhnHQOqNdHCCEeZfI=,iv:MEccVhU1Zp1AWUxU+BQIqQcpE6fzli2Jlmcdamin8eg=,tag:G3I9whLK2Q5q6DwLnraWgA==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-secret
    namespace: keycloak
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Zm/1cK337bY=,iv:d+MdTONshSCfHaDs3p+4APHLa9hRUG4PBC+mz59cxVU=,tag:4VnYTpIeLZNdmi5JpIzuzQ==,type:str]
    password: ENC[AES256_GCM,data:rcwQQ+uZMulCzYvV41r7,iv:iwX2APUR1KgqyWxT58lBdI4e+2qRHTHxfSTBOZfRVEM=,tag:iSlQ8RZyo7/YeF4CBxD0Ug==,type:str]
    jdbc-uri: ENC[AES256_GCM,data:4dcReqtvnOLQvikEF0hwR/UB0u6I7J5whwELv5KRnHO5cGRoBVgcnuqmSbjMRitzmCYESZbCuDTtRjkxRuKt0XWKqfI8mk/tdMdSG9WB,iv:EHKpA5s/o9+1H8HEXfA86s2CFoNAHCjknS8NY+KQTSs=,tag:flXHemLrrT3K2mW/3QO0OA==,type:str]
sops:
    age:
        - recipient: age14e9960ys3tqpnr40memrdp8uac0f86wv326ykwkwrufgrv4a5dtsd58zd2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubVdNSVV5MkxKK2NYMlJw
            Zm9sMVU4STcvUkdLYVcxQ3hOa3g2WlVWMTFzCkRDcnFwQ2xOOVJ5TE51UHU2TndV
            Sm5GVDhFY0RkQSt2cVlkZUU3TXpkcWcKLS0tIFZaNnd2RnRReVlaZFk5OE8yKzlV
            cFpoUHNSTVR4UEtySituZDlWR3U2dTgKZLTjkdlg0ZrIntO9+apI9NMWU4ahOwac
            BqY7rpcTd/Nzy5fyPfbsaMy43Fet9dkvuI7DEzZiaWuGltlKpHWz0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T10:35:40Z"
    mac: ENC[AES256_GCM,data:zLG5aBgN0dIwt5fw/Clb34Ajv8GgmD3nNcVqlrm4Y81QIxcC3TDXrzgGllODcO5LTiF7gReeexYPTZsg57baaqtMnk7DaqYgjXYG6aJ7rfpKuYp/7a5X9kgW4ghJMp88/3PdtxJWEq0nBu3O297rMZ1s+/VhnHQOqNdHCCEeZfI=,iv:MEccVhU1Zp1AWUxU+BQIqQcpE6fzli2Jlmcdamin8eg=,tag:G3I9whLK2Q5q6DwLnraWgA==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.12.1
