---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-manager-cluster-issuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ENC[AES256_GCM,data:fInHfkU2Ap68+pIv2xBW8A0k,iv:84WoMWxl1NVsElVlOjnMmsN9P3Mx/i4SewZNcMrqzts=,tag:C8GV1vs/mLl4ykSHuy2hVg==,type:str]
    privateKeySecretRef:
      name: cert-manager-cluster-issuer
    solvers:
      - dns01:
          cloudflare:
            email: ENC[AES256_GCM,data:xXopH9trrZT5AAiF66erm0ns,iv:aHWvw2qXURbse+wGDsYGv726MYM20Q5VPQP8FBwneLk=,tag:M1ZejfUcozrXFSoVvPuwJg==,type:str]
            apiTokenSecretRef:
              name: cert-manager-cloudflare-token
              key: cloudflare-token
        selector:
          dnsZones:
            - mariosl.dev
sops:
  age:
    - recipient: age14e9960ys3tqpnr40memrdp8uac0f86wv326ykwkwrufgrv4a5dtsd58zd2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTblpxVmx5dTc5R01LeHVl
        bk1TeUMxVHFGQ2YyVlBGZGhKV3R3ZDIzSldrClZ1TEJrVmdqZW1NWFVTS2prZDVp
        ZEU4aHUvaG1zcENVL2U3MHNWMzNyMm8KLS0tIGdBREdaOFU0MjM5SSt6UWkweUtx
        K0Fkd3NVTklFcWpUU1FNQ29Vc3Z6bzgKGH3teWPCeMQKGE/J3gKY3kWXQXyr51rz
        751CCFLxl48H+XR2qA3zKVgj9vwCKNokuRH7WwqWL3fHxo5OVj4/qg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-13T17:19:29Z"
  mac: ENC[AES256_GCM,data:rC8+wia3+oDSjJM+W+AHP+aEjGMTQbmy3RrIkjq9QShgiN0Ye2ka1DfQ5aPld/az2cxHIDt5gFjW6RY4lv8r5KM9+JIxR0NJyMweNJOnxBQQYPL1P03PYxYorFsfx3BlKUpKH1zT/EveI26FS7BlaxsFh/5L+0VfzX5TN1x1qJU=,iv:7JjjIEvx6s0MvaYstWxC3M4cxYpZj+6yc+icebzp8Ow=,tag:+70L5H/ymLJvDdI7DvZoog==,type:str]
  encrypted_regex: ^(data|stringData|email)$
  version: 3.12.1
