---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb-system-helmrelease
  namespace: metallb-system
spec:
  interval: 10m0s
  chart:
    spec: 
      chart: metallb
      version: 0.15.3
      sourceRef:
        kind: HelmRepository
        name: metallb-system-helmrepository
        namespace: flux-system
