http:
 #region routers
  routers:
    service:
      entryPoints:
        - "https"
      rule: "Host(`service.local.${DOMAIN}`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: service
#endregion
#region services
  services:
    service:
      loadBalancer:
        servers:
          - url: "https://192.0.2.1:1234"
        passHostHeader: true
#endregion
  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipAllowList:
        sourceRange:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers