---
apiVersion: v1
kind: Secret
metadata:
  name: checkmk-secret
  namespace: checkmk
type: Opaque
stringData:
  CMK_PASSWORD: ENC[AES256_GCM,data:PX9ThCJeTshlA3dfuX/iF1jf0xq7DE+aYV+d54QGZ8HJx+BWX24=,iv:OBLa3h99M7DagLlkf0QQPxfQ5z7wXZ3AT9XW9XnzSSw=,tag:QJ1hE6e1DGSmC8wn14CF3w==,type:str]
sops:
  age:
    - recipient: age14e9960ys3tqpnr40memrdp8uac0f86wv326ykwkwrufgrv4a5dtsd58zd2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQk5EdUk5MGU2TWwvSlIr
        TWFJS3JUcHhkaHI0YndDSVR0UUJ3RHZXcDBrCjdLUmtMYjd4anljS0xZcjdkQ1F2
        QUcvVW9TQVJtbWVVc1BscWcwV3Z5L1kKLS0tIG5CZGR5cE9QV2U0Qlg2U2xKNEwx
        eE9BUUIwS2N3WGpTeTlYdGdFcWdrZFkK0n8XLHas+GRSLRNgHl4QM6jQK8SNbL2s
        tLoeuOmVVZqIvxnGJU8LgmflrKEFKL2hqijSsaNmqpy05YDG8c+z7A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-18T07:32:11Z"
  mac: ENC[AES256_GCM,data:uO1e20jWU0uHh0UgNGmbSmB+W+INoqA4Z7FzvSaGqrAs75WykXKsmcq94ihSL5DPdWJz/WtvhRI4A1wqqczAMprhEsdCXBte0XA+Emclpa/fUGbNJJNNm5LrFCuLH+UxWS1IC5ANM9mata+ckpQxJx6vG2t1dNYwFeLkHpN2pEM=,iv:GYiI0A4bFVlio5OvA8fzk+bd/35rJBHN08tTe0+eFJw=,tag:eF9PjY7jOJ77L8sZ11KCeg==,type:str]
  encrypted_regex: ^(data|stringData|email)$
  version: 3.12.1
