---
name: test

on:
  pull_request:
    paths:
      - "**/*.yaml"
  push:
    paths:
      - "**/*.yaml"

permissions: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Setup yq
        uses: fluxcd/pkg/actions/yq@978262ecd0f3caca9b5bda5791a8fa83c5b31f61

      - name: Setup kubeconform
        uses: fluxcd/pkg/actions/kubeconform@978262ecd0f3caca9b5bda5791a8fa83c5b31f61

      - name: Setup kustomize
        uses: fluxcd/pkg/actions/kustomize@978262ecd0f3caca9b5bda5791a8fa83c5b31f61

      - name: Validate manifests
        run: ./scripts/validate.sh
